# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "BB3P875zlz9LowEWqrB703rYMUMi345+s9wsdQcaJvUA0rDqP/Hzu8zK9fbvANIMNuGBZakda7eLqnTnXsIsyLTWz2YiYok+tLXUQ2fzfG2l11UTOn9I1FcqjjK6E4ce0T4At03RuSoR82g2I7M3YwQtPZ1JsMi5CrI4rKiGcfx//qFKKCdObaalfmv01E8KDAxOpESglO3TVU+lsS+3b5CipTmnMZYK7rRNnePKk7713iYvqRB27Q8qaTfJqNDwU2uVNREuGw6V86viYPN7pWSxePfR6rnx479GQikxNP8NmxNzLGWeOVQQk/1U+HekrSpXzrlhve1q3u+ii2VVaAK7NGHvcfC2o07FPh0Dm1llJDv6B3waix2GuMXYj51OeVWwLrDHN+q3IMUyl/9X6hvmlkZUSY0M/39olBNRHTqtjywCE2NEgmXTYYJBD0vbkrRl45U9D/k2aZt/HRcRanmzb8pn2/IvpoulHX2+yvBqTUkm0WwzcvfQeZ62F2z7c8F2tTvXr74grMkPpIy0pXn/dPLMEStuU4dihj5qJyLyfGuul9FtKBkkVOytujAcL2PbWrlC53/HjzfMbknifHrfK7zomeGeTfzirGzRQ+TjoWvC6yjhkzWzCFJ8wFze15oHDdtFxYgOBjDb+f1DD80LmdjoxKiPVxdPfYaCzOo="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
