travis:
  secure:
    BINSTAR_TOKEN: BB3P875zlz9LowEWqrB703rYMUMi345+s9wsdQcaJvUA0rDqP/Hzu8zK9fbvANIMNuGBZakda7eLqnTnXsIsyLTWz2YiYok+tLXUQ2fzfG2l11UTOn9I1FcqjjK6E4ce0T4At03RuSoR82g2I7M3YwQtPZ1JsMi5CrI4rKiGcfx//qFKKCdObaalfmv01E8KDAxOpESglO3TVU+lsS+3b5CipTmnMZYK7rRNnePKk7713iYvqRB27Q8qaTfJqNDwU2uVNREuGw6V86viYPN7pWSxePfR6rnx479GQikxNP8NmxNzLGWeOVQQk/1U+HekrSpXzrlhve1q3u+ii2VVaAK7NGHvcfC2o07FPh0Dm1llJDv6B3waix2GuMXYj51OeVWwLrDHN+q3IMUyl/9X6hvmlkZUSY0M/39olBNRHTqtjywCE2NEgmXTYYJBD0vbkrRl45U9D/k2aZt/HRcRanmzb8pn2/IvpoulHX2+yvBqTUkm0WwzcvfQeZ62F2z7c8F2tTvXr74grMkPpIy0pXn/dPLMEStuU4dihj5qJyLyfGuul9FtKBkkVOytujAcL2PbWrlC53/HjzfMbknifHrfK7zomeGeTfzirGzRQ+TjoWvC6yjhkzWzCFJ8wFze15oHDdtFxYgOBjDb+f1DD80LmdjoxKiPVxdPfYaCzOo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
