travis:
  secure:
    BINSTAR_TOKEN: dNDOnHkaeresngp2RifVXtAzLwVKmKyuPCxuVbGN/NJTR8u2PfYkGjTzsyRB7HKfUymTKhTnyxscDgcNZtOXEqZr7QojzvZZFtBmZu/itgy2NAfPgHTxjvTxrZ4osB+ICzBKlbjidsEWrGGUn2sB/qfab4u0l2AkDJeatZAFi6FtDGkj3jVf80L4nXshQQhDDKs454PFEF7/n1dJwwch2aohDtfxpLcFo2Nt0LvNRrCKCPVXVJWu8Y8TSJQ3L/h/MvSLmmXxfms6q8fEDNPlYsiNwt6xVOLgRAj+fw6iIVSdEAnDoDarVf8c57moqdfPZa5e4IRnnDF4AO++vGpUPccZn86pQMB2WZ37gjeRewua9/rCa9N/cIpgQ/i4XdJLsPvLuJ0+5HevooxGUVjh7oPc3mm7WCfUaAKjudmbmbCG8ZHbhcgXUK61z8JAEz0TvCGtIYVOYS8p0QuCVUh+rXH9mcBXUAa2Tc24TS9Lvp3lUCX/wBDcyItbmQQqKwkMS70KGcxke8m7q5rXevhM0u+3CsvnUQgZe2RRcesZyYoEHH4xldd5yyjcwlptXYbeQ2u/j6qbBtSVdI/dTzD+lH2Ox4+Bdeq3VMpapkoTiK3olHJvGEPax5erJ0xnDcn/eUwXLfhSySd9WZuDBdVrDkl0qrWY6V/nzYIhNVlf/gU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
